language: python
python:
- '2.7'
- '3.6'
env:
    global:
        # Set defaults to avoid repeating in most cases
        - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - NUMPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='pillow gdal xarray dask toolz mock coverage coveralls codecov'
        - SETUP_XVFB=False
        - EVENT_TYPE='push pull_request'
        - SETUP_CMD='test'
        - CONDA_CHANNELS='conda-forge'
install:
# Get rasterio 1.0
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - conda install -c conda-forge/label/dev rasterio
script: coverage run --source=trollimage setup.py test
after_success:
    - if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: "Cpo7kPgjbyWKNRjnzWDggxo5dqG8KdtcrBxYWwBpkkhgly/ngN9EkjIdscrwmp8sCqfjTd0RGyR811k6dzU7kKJVbc6V309+4mG8O0w4IvfHCn+NaHymAMrHleRIqyxbo5kvrBZoX+eB7YWOUppF6ofeohbrNWWgMQv+/d+Mufs="
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      repo: pytroll/trollimage
      tags: true
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
